INSERT INTO `menu` (`id`, `name`, `parent_id`, `menu_order`, `icon`) VALUES
(1, '여성 의류', NULL, 1, 'fa-solid fa-house'),
(2, '남성 의류', NULL, 2, 'fa-solid fa-magnifying-glass'),
(3, '액세서리', NULL, 3, 'fa-solid fa-user'),
(4, '상의', 1, 2, 'fa-solid fa-check'),
(5, '아우터', 1, 1, 'fa-solid fa-download'),
(6, '바지', 2, 2, 'fa-brands fa-twitter'),
(7, '아우터', 2, 1, 'fa-solid fa-image'),
(8, '신발', 3, 2, 'fa-solid fa-shirt'),
(9, '가방', 3, 1, 'fa-solid fa-crown'),
(10, '코트', 7, 1, 'fa-solid fa-socks'),
(11, '자켓', 7, 2, 'fa-solid fa-mitten'),
(12, '블라우스', 4, 1, 'fa-solid fa-hat-wizard'),
(13, '코트', 5, 1, 'fa-solid fa-graduation-cap'),
(14, '패딩', 5, 2, 'fa-solid fa-glasses'),
(15, '청바지', 6, 1, 'fa-solid fa-vest-patches'),
(16, '크로스백', 9, 1, 'fa-solid fa-shoe-prints'),
(17, '스니커즈', 8, 1, 'fa-solid fa-hat-cowboy-side'),
(18, '샌들', 8, 3, 'fa-solid fa-hat-cowboy'),
(19, '부츠', 8, 2, 'fa-solid fa-compass-drafting'),
(20, '셔츠', 4, 2, 'fa-regular fa-heart');
