INSERT INTO `menu` (`id`, `name`, `parent_id`, `menu_order`, `icon`) VALUES
(1, '여성 의류', NULL, 0, 'fa-solid fa-house'),
(2, '남성 의류', NULL, 1, 'fa-solid fa-magnifying-glass'),
(3, '액세서리', NULL, 2, 'fa-solid fa-user'),
(4, '상의', 1, 1, 'fa-solid fa-check'),
(5, '아우터', 1, 0, 'fa-solid fa-download'),
(6, '바지', 2, 1, 'fa-brands fa-twitter'),
(7, '아우터', 2, 0, 'fa-solid fa-image'),
(8, '신발', 3, 1, 'fa-solid fa-shirt'),
(9, '가방', 3, 0, 'fa-solid fa-crown'),
(10, '코트', 7, 0, 'fa-solid fa-socks'),
(11, '자켓', 7, 1, 'fa-solid fa-mitten'),
(12, '블라우스', 4, 0, 'fa-solid fa-hat-wizard'),
(13, '코트', 5, 0, 'fa-solid fa-graduation-cap'),
(14, '패딩', 5, 1, 'fa-solid fa-glasses'),
(15, '청바지', 6, 0, 'fa-solid fa-vest-patches'),
(16, '크로스백', 9, 0, 'fa-solid fa-shoe-prints'),
(17, '스니커즈', 8, 0, 'fa-solid fa-hat-cowboy-side'),
(18, '샌들', 8, 2, 'fa-solid fa-hat-cowboy'),
(19, '부츠', 8, 1, 'fa-solid fa-compass-drafting'),
(20, '셔츠', 4, 1, 'fa-regular fa-heart'),
(21, '배낭', 9, 1, 'fa-solid fa-vest-patches'),
(22, '애플파우치', 9, 2, 'fa-solid fa-hat-cowboy'),
(23, '노트북 가방', 9, 3, 'fa-solid fa-hat-cowboy-side'),
(24, '아이패드 가방', 9, 4, 'fa-solid fa-socks'),
(25, '운동 가방', 9, 5, 'fa-solid fa-mitten'),
(26, '스피커 가방', 9, 6, 'fa-solid fa-compass-drafting'),
(27, '안경 가방', 9, 7, 'fa-solid fa-mitten'),
(28, '책 가방', 9, 8, 'fa-solid fa-hat-wizard'),
(29, '컵 가방', 9, 9, 'fa-solid fa-vest-patches'),
(30, '운동화', 8, 3, 'fa-brands fa-twitter'),
(31, '슬리퍼', 8, 4, 'fa-solid fa-crown'),
(32, '컨버스', 8, 5, 'fa-solid fa-check'),
(33, '나이키', 8, 6, 'fa-solid fa-shirt'),
(34, '반스', 8, 7, 'fa-solid fa-mitten'),
(35, '크록스', 8, 8, 'fa-solid fa-magnifying-glass'),
(36, '러너', 8, 9, 'fa-solid fa-compass-drafting');