INSERT INTO `menu` (`name`, `parent_id`, `menu_order`, `icon`) VALUES
('여성 의류', NULL, 1, 'fa-solid fa-house'),
('남성 의류', NULL, 2, 'fa-solid fa-magnifying-glass'),
('액세서리', NULL, 3, 'fa-solid fa-user'),
('상의', 1, 2, 'fa-solid fa-check'),
('아우터', 1, 1, 'fa-solid fa-download'),
('바지', 2, 2, 'fa-brands fa-twitter'),
('아우터', 2, 1, 'fa-solid fa-image'),
('신발', 3, 2, 'fa-solid fa-shirt'),
('가방', 3, 1, 'fa-solid fa-crown'),
('코트', 4, 1, 'fa-solid fa-socks'),
('자켓', 4, 2, 'fa-solid fa-mitten'),
('블라우스', 5, 1, 'fa-solid fa-hat-wizard'),
('코트', 6, 1, 'fa-solid fa-graduation-cap'),
('패딩', 6, 2, 'fa-solid fa-glasses'),
('청바지', 7, 1, 'fa-solid fa-vest-patches'),
('크로스백', 8, 1, 'fa-solid fa-shoe-prints'),
('스니커즈', 9, 1, 'fa-solid fa-hat-cowboy-side'),
('샌들', 9, 3, 'fa-solid fa-hat-cowboy'),
('부츠', 9, 2, 'fa-solid fa-compass-drafting'),
('셔츠', 5, 2, 'fa-regular fa-heart');
